            - name: Dependencies Autoupdate
  # You may pin to the exact commit or the version.
  # uses: romoh/dependencies-autoupdate@cd210e4a6d66047abd2904b9332d6ed82fb78fab
  uses: romoh/dependencies-autoupdate@v1.2
  with:
    # Token used to send pull requests
    token: 
    # Command to update dependencies and do initial checks
    update-command: 
    # Path to directory to run the update-command. If not provided defaults to root
    update-path: # optional
    # Command to run if dependencies update and changes were detected. This can be version increments or extra checks.
    on-changes-command: # optional
          
